collections:
  ############################
  #         POPULAR          #
  ############################

  IMDb Most Popular:
    imdb_chart: popular_shows
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*100"
    schedule: daily
  TMDb Most Popular:
    tmdb_popular: 100
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*101"
    schedule: daily
  Trakt Trending:
    trakt_trending: 30
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*102"
    schedule: daily

  ############################
  #         DISCOVER         #
  ############################

  Top Rated Animated Shows:
    tmdb_discover:
      limit: 30
      include_adult: false
      with_genres: 16
      with_original_language: en
      sort_by: vote_average.desc
      vote_count.gte: 100
      first_air_date.gte: 2010-01-01
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    summary: A collection of the highest rated animated TV shows
    sort_title: "*150"
    schedule: weekly

  Top Rated Family Shows:
    tmdb_discover:
      limit: 30
      include_adult: false
      with_genres: 10751
      sort_by: vote_average.desc
      vote_count.gte: 50
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    summary: A collection of the highest rated family-friendly TV shows
    sort_title: "*151"
    schedule: weekly

  ############################
  #          CUSTOM          #
  ############################

  Star Trek:
    tmdb_list: https://www.themoviedb.org/list/7071553
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*400"
    file_poster: config/assets/Star Trek-2.png
    schedule: monthly(10)
  Star Wars (Animated):
    tmdb_list: https://www.themoviedb.org/list/7091278
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*401"
    schedule: monthly(10)
  Star Wars (Live Action):
    tmdb_list: https://www.themoviedb.org/list/8173369
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*402"
    schedule: monthly(10)
  Classic Cartoons:
    tmdb_list: https://www.themoviedb.org/list/7088117
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*403"
    schedule: yearly(01/30)
  Nature Documentary:
    tmdb_list: https://www.themoviedb.org/list/7087971
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*404"
    schedule: monthly(10)
  Prison:
    tmdb_list: https://www.themoviedb.org/list/7104835
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*405"
    schedule: monthly(10)
  Arrowverse:
    tmdb_list: https://www.themoviedb.org/list/7109881
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*406"
    schedule: monthly(10)
  Baking:
    tmdb_list: https://www.themoviedb.org/list/8168660
    tvdb_show:
      - 407030
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*407"
    schedule: monthly(10)
  My Favorite TV Shows:
    tmdb_list: https://www.themoviedb.org/list/7111217
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*450"
    schedule: monthly(10)

  ############################
  #         STUDIOS          #
  ############################

  Marvel:
    tmdb_list: https://www.themoviedb.org/list/7071556
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*500"
    schedule: weekly(friday)
  Marvel Studios:
    tmdb_company: 420
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*501"
    schedule: weekly(friday)
  DC:
    tmdb_list: https://www.themoviedb.org/list/7071946
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*502"
    schedule: weekly(friday)

  ############################
  #         NETWORKS         #
  ############################

  Apple TV+:
    tmdb_network: 2552
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*700"
    schedule: daily
  Apple TV+ (Score):
    mdblist_list: https://mdblist.com/lists/awesomeaustn/apple-tv-sorted-by-score
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*700b"
    summary: Sorted by a combined score of IMDb, Trakt, TMDb, Letterboxed, Rotten Tomatoes, Audience, Metacritic, and RogerEbert.
    schedule: daily
  Netflix:
    tmdb_network: 213
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*701"
    schedule: daily
  Netflix (Score):
    mdblist_list: https://mdblist.com/lists/awesomeaustn/netflix-sorted-by-score
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*701b"
    summary: Sorted by a combined score of IMDb, Trakt, TMDb, Letterboxed, Rotten Tomatoes, Audience, Metacritic, and RogerEbert.
    schedule: daily
  Prime Video:
    tmdb_network: 1024
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*702"
    schedule: daily
  Hulu:
    tmdb_network: 453
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*703"
    schedule: daily
  Max:
    tmdb_network: 3186
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*704"
    summary: Formerly HBO Max
    schedule: daily
  Disney+:
    tmdb_network: 2739
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*705"
    schedule: daily
  Disney+ (Score):
    mdblist_list: https://mdblist.com/lists/awesomeaustn/disney-sorted-by-score
    sync_mode: sync
    collection_mode: default
    collection_order: custom
    sort_title: "*705b"
    summary: Sorted by a combined score of IMDb, Trakt, TMDb, Letterboxed, Rotten Tomatoes, Audience, Metacritic, and RogerEbert.
    schedule: daily
  Paramount+:
    tmdb_network: 4330
    sync_mode: sync
    collection_mode: default
    collection_order: release
    sort_title: "*706"
    schedule: daily

  ############################
  #          GENRES          #
  ############################

  Comedy:
    plex_search:
      all:
        genre: Comedy
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*200"
    summary: A collection of Comedy TV Shows
    schedule: weekly(friday)
  Good Comedy:
    plex_search:
      all:
        genre: Comedy
        rating.gte: 8
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*201"
    summary: A collection of Comedy TV Shows with a rating of 8 and higher
    schedule: weekly(friday)
  Drama:
    plex_search:
      all:
        genre: Drama
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*202"
    summary: A collection of Drama TV Shows
    schedule: weekly(friday)
  Good Drama:
    plex_search:
      all:
        genre: Drama
        rating.gte: 8
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*203"
    summary: A collection of Drama TV Shows with a rating of 8 and higher
    schedule: weekly(friday)
  Animation:
    plex_search:
      all:
        genre: Animation
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*204"
    summary: A collection of Animated TV Shows
    schedule: weekly(friday)
  Sci-Fi & Fantasy:
    plex_search:
      all:
        genre: Science Fiction
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*205"
    summary: A collection of Science Fiction TV Shows
    schedule: weekly(friday)

  ############################
  #          YEARS           #
  ############################

  2020 Shows:
    plex_search:
      all:
        year: 2020
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows in 2020
    sort_title: "*300"
    schedule: weekly(friday)
  2021 Shows:
    plex_search:
      all:
        year: 2021
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows in 2021
    sort_title: "*301"
    schedule: weekly(friday)
  2022 Shows:
    plex_search:
      all:
        year: 2022
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows in 2022
    sort_title: "*302"
    schedule: weekly(friday)
  2023 Shows:
    plex_search:
      all:
        year: 2023
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows in 2023
    sort_title: "*303"
    schedule: weekly(friday)
  2024 Shows:
    plex_search:
      all:
        year: 2024
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows premiered in 2024
    sort_title: "*304"
    schedule: daily
  2025 Shows:
    plex_search:
      all:
        year: 2025
    sync_mode: sync
    collection_mode: default
    collection_order: release
    summary: A collection of TV shows premiering in 2025
    sort_title: "*305"
    schedule: daily
    
  ############################
  #          STATUS          #
  ############################

  Currently Airing:
    plex_all: true
    filters:
      status: airing
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*600"
    schedule: weekly
    
  Recently Ended:
    plex_all: true
    filters:
      status: ended
      year.gte: 2022
    sync_mode: sync
    collection_mode: default
    collection_order: alpha
    sort_title: "*601"
    schedule: weekly

############################
#          AUDIO           #
############################

############################
#          ACTORS          #
############################

############################
#        DIRECTORS         #
############################

############################
#          DOLBY           #
############################

#  Dolby Atmos & Dolby Vision:
#    mdblist_list: https://mdblist.com/lists/blisskodi/dolby-atmos-dolby-vision-tv
#    sync_mode: sync
#    collection_mode: default
#    collection_order: custom
#    sort_title: "*952"
#    schedule: weekly(friday)
#   The default sort_by when it's not specified is score.desc
